package com.yekong.im.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yekong.im.db.UserInfoEntity;
import com.yekong.im.db.GroupInfoEntity;
import com.yekong.im.db.SystemNotifyEntity;

import com.yekong.im.db.UserInfoEntityDao;
import com.yekong.im.db.GroupInfoEntityDao;
import com.yekong.im.db.SystemNotifyEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoEntityDaoConfig;
    private final DaoConfig groupInfoEntityDaoConfig;
    private final DaoConfig systemNotifyEntityDaoConfig;

    private final UserInfoEntityDao userInfoEntityDao;
    private final GroupInfoEntityDao groupInfoEntityDao;
    private final SystemNotifyEntityDao systemNotifyEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoEntityDaoConfig = daoConfigMap.get(UserInfoEntityDao.class).clone();
        userInfoEntityDaoConfig.initIdentityScope(type);

        groupInfoEntityDaoConfig = daoConfigMap.get(GroupInfoEntityDao.class).clone();
        groupInfoEntityDaoConfig.initIdentityScope(type);

        systemNotifyEntityDaoConfig = daoConfigMap.get(SystemNotifyEntityDao.class).clone();
        systemNotifyEntityDaoConfig.initIdentityScope(type);

        userInfoEntityDao = new UserInfoEntityDao(userInfoEntityDaoConfig, this);
        groupInfoEntityDao = new GroupInfoEntityDao(groupInfoEntityDaoConfig, this);
        systemNotifyEntityDao = new SystemNotifyEntityDao(systemNotifyEntityDaoConfig, this);

        registerDao(UserInfoEntity.class, userInfoEntityDao);
        registerDao(GroupInfoEntity.class, groupInfoEntityDao);
        registerDao(SystemNotifyEntity.class, systemNotifyEntityDao);
    }
    
    public void clear() {
        userInfoEntityDaoConfig.clearIdentityScope();
        groupInfoEntityDaoConfig.clearIdentityScope();
        systemNotifyEntityDaoConfig.clearIdentityScope();
    }

    public UserInfoEntityDao getUserInfoEntityDao() {
        return userInfoEntityDao;
    }

    public GroupInfoEntityDao getGroupInfoEntityDao() {
        return groupInfoEntityDao;
    }

    public SystemNotifyEntityDao getSystemNotifyEntityDao() {
        return systemNotifyEntityDao;
    }

}
